Implement `skip_until_keyframe?` option
membraneframework/membrane_h264_plugin pull request #35
Opened 2023-06-30 10:47 UTC by varsill

2023-07-10 15:09 UTC, mat-hek requested changes

2023-07-10 15:09 UTC, mat-hek commented on lib/membrane_h264_plugin/parser.ex
> +      Enum.reduce(aus, {[], state}, fn au, {actions_acc, state} ->
change to flat_map_reduce

2023-07-11 13:56 UTC, varsill commented on lib/membrane_h264_plugin/parser/nalu_parser.ex
> -      has_seen_keyframe?: has_seen_keyframe?
done

2023-07-11 14:01 UTC, varsill commented on lib/membrane_h264_plugin/parser.ex
> +      Enum.reduce(aus, {[], state}, fn au, {actions_acc, state} ->
done

2023-07-11 14:11 UTC, mat-hek approved these changes

2023-07-11 14:11 UTC, merged